[package]
name = "enclave_verifier"
version = "0.1.0"
authors = ["Hunter Coffman", "Haofan Zheng"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
